name: kirubashankar-api

region: nyc

domains:
  - domain: api.kirubashankar.com
    type: PRIMARY

services:
  - name: api
    github:
      repo: kirubae/kirubashankar
      branch: main
      deploy_on_push: true
    source_dir: api
    dockerfile_path: api/Dockerfile

    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs

    routes:
      - path: /

    envs:
      - key: CORS_ORIGINS
        value: "https://kirubashankar.com,http://localhost:4321"
      - key: PERPLEXITY_API_KEY
        type: SECRET
      - key: R2_ACCESS_KEY_ID
        type: SECRET
      - key: R2_SECRET_ACCESS_KEY
        type: SECRET
      - key: R2_BUCKET_NAME
        value: "data-merge-uploads"
      - key: R2_ENDPOINT
        value: "https://eeb01e3413d58a8b987623ee7e39a2b7.r2.cloudflarestorage.com"

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
